In [2]:
## Min residual^2 = (y(actual) - y(estimated))^2  = rTr where r = residual
## Solution of the same is XT X Theta = XTy ## Solve for theta -->coeffcients

In [4]:
import numpy as np

In [5]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b

In [14]:
#myfunc([1, 2, 3, 4], 2) ##this doesn't work


In [16]:
# try:
#     myfunc(np.array([1, 2, 3, 4]), 2)
# except TypeError:
#     print("TypeError raised")


In [8]:
vfunc = np.vectorize(myfunc)


In [9]:
vfunc([1, 2, 3, 4], 2)


array([3, 4, 1, 2])

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.cumprod(a, axis=0)

array([[ 1,  2,  3],
       [ 4, 10, 18]], dtype=int32)

In [20]:
np.cumprod(a, axis=1)

array([[  1,   2,   6],
       [  4,  20, 120]], dtype=int32)

In [21]:
np.tile(np.arange(10).reshape(10,1),reps = (1,2))

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [23]:
## Converting equation to formula
## Np.vectorize
## Solving linear equations through
## i) np.linalg.lstsq()
## ii) Decomposition into QR matrix
## iii) Offline vs online theta computation